/*************************************************************************************************
*  Database Pgm Using Java - ITC-5201-RNB – Assignment 2                                                                                                                            *

*  I declare that this assignment is my own work in accordance with Humber Academic Policy.        *

*  No part of this assignment has been copied manually or electronically from any other source       *

*  (including web sites) or distributed to other students/social media.                                                       *
                                                                                                                                                                             
*  Name:Abhi Hasmukhbhai Patel Student ID: N01421293      Date: June 14, 2021 
* 
*  Name: Harshil Hemantkumar Parmar Student ID: N01444692      Date: June 14, 2021

* *************************************************************************************************/

package gui;

import data.CustomerData;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import method.CustomerMethod;
import method.ValidationMethod;

public class MainApplicationForm extends javax.swing.JFrame {

    CustomerMethod customerMethod = new CustomerMethod();

    ValidationMethod validationMethod = new ValidationMethod();

    boolean isNameFieldVaild;
    boolean isPhoneFieldVaild;
    boolean isEmailFieldVaild;
    boolean isPostalCodeFieldVaild;

    /**
     * Creates new form MainApplicationForm
     */
    public MainApplicationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        menuTitlePanel = new javax.swing.JPanel();
        menuTitleLabel = new javax.swing.JLabel();
        addCustomerMenuButton = new javax.swing.JButton();
        searchEditCustomerMenuButton = new javax.swing.JButton();
        viewAllCustomeMenuButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        addCustomerPanel = new javax.swing.JPanel();
        addCustomerTitlePanel = new javax.swing.JPanel();
        addCustomerTitleLabel = new javax.swing.JLabel();
        addCustomerControlsPanel = new javax.swing.JPanel();
        nameLabel_add = new javax.swing.JLabel();
        nameTextField_add = new javax.swing.JTextField();
        errorLabel_name_add = new javax.swing.JLabel();
        phoneLabel_add = new javax.swing.JLabel();
        phoneTextField_add = new javax.swing.JTextField();
        errorLabel_phone_add = new javax.swing.JLabel();
        emailLabel_add = new javax.swing.JLabel();
        emailTextField_add = new javax.swing.JTextField();
        errorLabel_email_add = new javax.swing.JLabel();
        postalCodeLabel_add = new javax.swing.JLabel();
        postalCodeTextField_add = new javax.swing.JTextField();
        errorLabel_posatlCode_add = new javax.swing.JLabel();
        clearButton_add = new javax.swing.JButton();
        addCustomerButton_add = new javax.swing.JButton();
        addResultLabel = new javax.swing.JLabel();
        searchCustomerPanel = new javax.swing.JPanel();
        searchCustomerTitlePanel = new javax.swing.JPanel();
        searchCustomerTitleLabel = new javax.swing.JLabel();
        searchCustomerControlsPanel = new javax.swing.JPanel();
        searchControlsPanel = new javax.swing.JPanel();
        customerIdLabel_search = new javax.swing.JLabel();
        customerIdTextField_search = new javax.swing.JTextField();
        errorLabel_cutomerId_search = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        searchResultPanel = new javax.swing.JPanel();
        searchResultScrollPane = new javax.swing.JScrollPane();
        searchResultTextArea = new javax.swing.JTextArea();
        searchResultLabel = new javax.swing.JLabel();
        editCustomerLink = new javax.swing.JLabel();
        editCustomerPanel = new javax.swing.JPanel();
        editCustomerTitlePanel = new javax.swing.JPanel();
        editCustomerTitleLabel = new javax.swing.JLabel();
        editCustomerControlsPanel = new javax.swing.JPanel();
        nameLabel_edit = new javax.swing.JLabel();
        nameTextField_edit = new javax.swing.JTextField();
        errorLabel_name_edit = new javax.swing.JLabel();
        phoneLabel_edit = new javax.swing.JLabel();
        phoneTextField_edit = new javax.swing.JTextField();
        errorLabel_phone_edit = new javax.swing.JLabel();
        emailLabel_edit = new javax.swing.JLabel();
        emailTextField_edit = new javax.swing.JTextField();
        errorLabel_email_edit = new javax.swing.JLabel();
        postalCodeLabel_edit = new javax.swing.JLabel();
        postalCodeTextField_edit = new javax.swing.JTextField();
        errorLabel_posatlCode_edit = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        editCustomerButton = new javax.swing.JButton();
        customerData_index = new javax.swing.JLabel();
        edit_success = new javax.swing.JLabel();
        viewAllCustomerPanel = new javax.swing.JPanel();
        viewAllCustomerTitlePanel = new javax.swing.JPanel();
        viewAllCustomerTitleLabel = new javax.swing.JLabel();
        viewAllCustomerControlsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewAllCustomerTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Management  Application");

        menuPanel.setBackground(new java.awt.Color(49, 49, 49));
        menuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 49, 49)));
        menuPanel.setForeground(new java.awt.Color(255, 255, 255));

        menuTitlePanel.setBackground(new java.awt.Color(202, 62, 71));
        menuTitlePanel.setForeground(new java.awt.Color(255, 255, 255));

        menuTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuTitleLabel.setText("Menu");
        menuTitlePanel.add(menuTitleLabel);

        addCustomerMenuButton.setBackground(new java.awt.Color(73, 73, 73));
        addCustomerMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addCustomerMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerMenuButton.setText("Add Customer");
        addCustomerMenuButton.setOpaque(false);
        addCustomerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMenuButtonActionPerformed(evt);
            }
        });

        searchEditCustomerMenuButton.setBackground(new java.awt.Color(73, 73, 73));
        searchEditCustomerMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchEditCustomerMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        searchEditCustomerMenuButton.setText("Search / Edit Customer");
        searchEditCustomerMenuButton.setOpaque(false);
        searchEditCustomerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditCustomerMenuButtonActionPerformed(evt);
            }
        });

        viewAllCustomeMenuButton1.setBackground(new java.awt.Color(73, 73, 73));
        viewAllCustomeMenuButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewAllCustomeMenuButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewAllCustomeMenuButton1.setText("View All Customers");
        viewAllCustomeMenuButton1.setOpaque(false);
        viewAllCustomeMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllCustomeMenuButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchEditCustomerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAllCustomeMenuButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCustomerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(menuTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCustomerMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(searchEditCustomerMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewAllCustomeMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, java.awt.BorderLayout.LINE_START);

        mainPanel.setBackground(new java.awt.Color(82, 82, 82));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        addCustomerPanel.setOpaque(false);
        addCustomerPanel.setLayout(new java.awt.BorderLayout());

        addCustomerTitlePanel.setBackground(new java.awt.Color(202, 62, 71));
        addCustomerTitlePanel.setForeground(new java.awt.Color(255, 255, 255));

        addCustomerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addCustomerTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerTitleLabel.setText("Add Customer");
        addCustomerTitlePanel.add(addCustomerTitleLabel);

        addCustomerPanel.add(addCustomerTitlePanel, java.awt.BorderLayout.PAGE_START);

        addCustomerControlsPanel.setOpaque(false);

        nameLabel_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel_add.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel_add.setText("Name");
        nameLabel_add.setName(""); // NOI18N

        nameTextField_add.setBackground(new java.awt.Color(82, 82, 82));
        nameTextField_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTextField_add.setForeground(new java.awt.Color(255, 255, 255));
        nameTextField_add.setCaretColor(new java.awt.Color(130, 130, 130));
        nameTextField_add.setName("add"); // NOI18N
        nameTextField_add.setOpaque(false);
        nameTextField_add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validateNameField(evt);
            }
        });

        errorLabel_name_add.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel_name_add.setText(" ");

        phoneLabel_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneLabel_add.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel_add.setText("Phone Number");

        phoneTextField_add.setBackground(new java.awt.Color(82, 82, 82));
        phoneTextField_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneTextField_add.setForeground(new java.awt.Color(255, 255, 255));
        phoneTextField_add.setCaretColor(new java.awt.Color(130, 130, 130));
        phoneTextField_add.setName("add"); // NOI18N
        phoneTextField_add.setOpaque(false);
        phoneTextField_add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validatePhoneField(evt);
            }
        });
        phoneTextField_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                only10DigitsAllowed(evt);
            }
        });

        errorLabel_phone_add.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel_phone_add.setText(" ");

        emailLabel_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel_add.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel_add.setText("Email Address");

        emailTextField_add.setBackground(new java.awt.Color(82, 82, 82));
        emailTextField_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTextField_add.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField_add.setCaretColor(new java.awt.Color(130, 130, 130));
        emailTextField_add.setName("add"); // NOI18N
        emailTextField_add.setOpaque(false);
        emailTextField_add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validateEmailField(evt);
            }
        });

        errorLabel_email_add.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel_email_add.setText(" ");

        postalCodeLabel_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        postalCodeLabel_add.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeLabel_add.setText("Postal Code");

        postalCodeTextField_add.setBackground(new java.awt.Color(82, 82, 82));
        postalCodeTextField_add.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        postalCodeTextField_add.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeTextField_add.setCaretColor(new java.awt.Color(130, 130, 130));
        postalCodeTextField_add.setName("add"); // NOI18N
        postalCodeTextField_add.setOpaque(false);
        postalCodeTextField_add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validatePostalCodeField(evt);
            }
        });
        postalCodeTextField_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                only6CharAllowed(evt);
            }
        });

        errorLabel_posatlCode_add.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel_posatlCode_add.setText(" ");

        clearButton_add.setBackground(new java.awt.Color(73, 73, 73));
        clearButton_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearButton_add.setForeground(new java.awt.Color(255, 255, 255));
        clearButton_add.setText("Clear");
        clearButton_add.setOpaque(false);
        clearButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton_addActionPerformed(evt);
            }
        });

        addCustomerButton_add.setBackground(new java.awt.Color(73, 73, 73));
        addCustomerButton_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addCustomerButton_add.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerButton_add.setText("Add Customer");
        addCustomerButton_add.setOpaque(false);
        addCustomerButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButton_addActionPerformed(evt);
            }
        });

        addResultLabel.setText(" ");

        javax.swing.GroupLayout addCustomerControlsPanelLayout = new javax.swing.GroupLayout(addCustomerControlsPanel);
        addCustomerControlsPanel.setLayout(addCustomerControlsPanelLayout);
        addCustomerControlsPanelLayout.setHorizontalGroup(
            addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerControlsPanelLayout.createSequentialGroup()
                .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCustomerControlsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel_add)
                            .addComponent(postalCodeLabel_add)
                            .addComponent(emailLabel_add))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerControlsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(phoneLabel_add)
                        .addGap(18, 18, 18)))
                .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addResultLabel)
                    .addComponent(errorLabel_posatlCode_add)
                    .addComponent(postalCodeTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorLabel_email_add)
                    .addComponent(errorLabel_phone_add)
                    .addComponent(errorLabel_name_add)
                    .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(emailTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerControlsPanelLayout.createSequentialGroup()
                            .addComponent(addCustomerButton_add)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        addCustomerControlsPanelLayout.setVerticalGroup(
            addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel_add)
                    .addComponent(nameTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(errorLabel_name_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel_add)
                    .addComponent(phoneTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(errorLabel_phone_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel_add))
                .addGap(1, 1, 1)
                .addComponent(errorLabel_email_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCodeTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeLabel_add))
                .addGap(5, 5, 5)
                .addComponent(errorLabel_posatlCode_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addResultLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        addCustomerPanel.add(addCustomerControlsPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(addCustomerPanel, "card2");

        searchCustomerPanel.setOpaque(false);
        searchCustomerPanel.setLayout(new java.awt.BorderLayout());

        searchCustomerTitlePanel.setBackground(new java.awt.Color(202, 62, 71));
        searchCustomerTitlePanel.setForeground(new java.awt.Color(255, 255, 255));

        searchCustomerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchCustomerTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchCustomerTitleLabel.setText("Search Customer");
        searchCustomerTitlePanel.add(searchCustomerTitleLabel);

        searchCustomerPanel.add(searchCustomerTitlePanel, java.awt.BorderLayout.PAGE_START);

        searchCustomerControlsPanel.setOpaque(false);

        searchControlsPanel.setOpaque(false);

        customerIdLabel_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerIdLabel_search.setForeground(new java.awt.Color(255, 255, 255));
        customerIdLabel_search.setText("Customer Id");

        customerIdTextField_search.setBackground(new java.awt.Color(82, 82, 82));
        customerIdTextField_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerIdTextField_search.setForeground(new java.awt.Color(255, 255, 255));
        customerIdTextField_search.setCaretColor(new java.awt.Color(130, 130, 130));
        customerIdTextField_search.setOpaque(false);

        errorLabel_cutomerId_search.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel_cutomerId_search.setText(" ");

        searchButton.setBackground(new java.awt.Color(73, 73, 73));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setOpaque(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchControlsPanelLayout = new javax.swing.GroupLayout(searchControlsPanel);
        searchControlsPanel.setLayout(searchControlsPanelLayout);
        searchControlsPanelLayout.setHorizontalGroup(
            searchControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchControlsPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(searchControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel_cutomerId_search)
                    .addComponent(customerIdTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(searchControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchControlsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(customerIdLabel_search)
                    .addContainerGap(361, Short.MAX_VALUE)))
        );
        searchControlsPanelLayout.setVerticalGroup(
            searchControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerIdTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel_cutomerId_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(searchControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchControlsPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(customerIdLabel_search)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        searchResultPanel.setOpaque(false);

        searchResultScrollPane.setMinimumSize(new java.awt.Dimension(100, 100));

        searchResultTextArea.setColumns(20);
        searchResultTextArea.setRows(5);
        searchResultTextArea.setEnabled(false);
        searchResultTextArea.setOpaque(false);
        searchResultScrollPane.setViewportView(searchResultTextArea);

        searchResultLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchResultLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchResultLabel.setText("Search Result");

        editCustomerLink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editCustomerLink.setForeground(new java.awt.Color(153, 153, 255));
        editCustomerLink.setText("Click here to edit customer details");
        editCustomerLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editCustomerLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCustomerLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchResultPanelLayout = new javax.swing.GroupLayout(searchResultPanel);
        searchResultPanel.setLayout(searchResultPanelLayout);
        searchResultPanelLayout.setHorizontalGroup(
            searchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(searchResultLabel)
                .addGap(18, 18, 18)
                .addGroup(searchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editCustomerLink)
                    .addComponent(searchResultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        searchResultPanelLayout.setVerticalGroup(
            searchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchResultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchResultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCustomerLink)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchCustomerControlsPanelLayout = new javax.swing.GroupLayout(searchCustomerControlsPanel);
        searchCustomerControlsPanel.setLayout(searchCustomerControlsPanelLayout);
        searchCustomerControlsPanelLayout.setHorizontalGroup(
            searchCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerControlsPanelLayout.createSequentialGroup()
                .addGroup(searchCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchCustomerControlsPanelLayout.setVerticalGroup(
            searchCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerControlsPanelLayout.createSequentialGroup()
                .addComponent(searchControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchCustomerPanel.add(searchCustomerControlsPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(searchCustomerPanel, "card2");

        editCustomerPanel.setOpaque(false);
        editCustomerPanel.setLayout(new java.awt.BorderLayout());

        editCustomerTitlePanel.setBackground(new java.awt.Color(202, 62, 71));
        editCustomerTitlePanel.setForeground(new java.awt.Color(255, 255, 255));

        editCustomerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        editCustomerTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        editCustomerTitleLabel.setText("Edit Customer");
        editCustomerTitlePanel.add(editCustomerTitleLabel);

        editCustomerPanel.add(editCustomerTitlePanel, java.awt.BorderLayout.PAGE_START);

        editCustomerControlsPanel.setOpaque(false);

        nameLabel_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel_edit.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel_edit.setText("Name");

        nameTextField_edit.setBackground(new java.awt.Color(82, 82, 82));
        nameTextField_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTextField_edit.setForeground(new java.awt.Color(255, 255, 255));
        nameTextField_edit.setCaretColor(new java.awt.Color(130, 130, 130));
        nameTextField_edit.setName("edit"); // NOI18N
        nameTextField_edit.setOpaque(false);
        nameTextField_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validateNameField(evt);
            }
        });

        errorLabel_name_edit.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel_name_edit.setText(" ");

        phoneLabel_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneLabel_edit.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel_edit.setText("Phone Number");

        phoneTextField_edit.setBackground(new java.awt.Color(82, 82, 82));
        phoneTextField_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneTextField_edit.setForeground(new java.awt.Color(255, 255, 255));
        phoneTextField_edit.setCaretColor(new java.awt.Color(130, 130, 130));
        phoneTextField_edit.setName("edit"); // NOI18N
        phoneTextField_edit.setOpaque(false);
        phoneTextField_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validatePhoneField(evt);
            }
        });
        phoneTextField_edit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                only10DigitsAllowed(evt);
            }
        });

        errorLabel_phone_edit.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel_phone_edit.setText(" ");

        emailLabel_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel_edit.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel_edit.setText("Email Address");

        emailTextField_edit.setBackground(new java.awt.Color(82, 82, 82));
        emailTextField_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTextField_edit.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField_edit.setCaretColor(new java.awt.Color(130, 130, 130));
        emailTextField_edit.setName("edit"); // NOI18N
        emailTextField_edit.setOpaque(false);
        emailTextField_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validateEmailField(evt);
            }
        });

        errorLabel_email_edit.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel_email_edit.setText(" ");

        postalCodeLabel_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        postalCodeLabel_edit.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeLabel_edit.setText("Postal Code");

        postalCodeTextField_edit.setBackground(new java.awt.Color(82, 82, 82));
        postalCodeTextField_edit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        postalCodeTextField_edit.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeTextField_edit.setCaretColor(new java.awt.Color(130, 130, 130));
        postalCodeTextField_edit.setName("edit"); // NOI18N
        postalCodeTextField_edit.setOpaque(false);
        postalCodeTextField_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validatePostalCodeField(evt);
            }
        });
        postalCodeTextField_edit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                only6CharAllowed(evt);
            }
        });

        errorLabel_posatlCode_edit.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel_posatlCode_edit.setText(" ");

        closeButton.setBackground(new java.awt.Color(73, 73, 73));
        closeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Close");
        closeButton.setOpaque(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        editCustomerButton.setBackground(new java.awt.Color(73, 73, 73));
        editCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        editCustomerButton.setText("Edit Customer");
        editCustomerButton.setOpaque(false);
        editCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerButtonActionPerformed(evt);
            }
        });

        customerData_index.setText("customerId_edit");

        edit_success.setText("edit_success");

        javax.swing.GroupLayout editCustomerControlsPanelLayout = new javax.swing.GroupLayout(editCustomerControlsPanel);
        editCustomerControlsPanel.setLayout(editCustomerControlsPanelLayout);
        editCustomerControlsPanelLayout.setHorizontalGroup(
            editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerControlsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerData_index)
                    .addGroup(editCustomerControlsPanelLayout.createSequentialGroup()
                        .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postalCodeLabel_edit)
                            .addComponent(emailLabel_edit)
                            .addComponent(phoneLabel_edit)
                            .addComponent(nameLabel_edit))
                        .addGap(30, 30, 30)
                        .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLabel_posatlCode_edit)
                            .addComponent(postalCodeTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorLabel_email_edit)
                            .addComponent(errorLabel_phone_edit)
                            .addComponent(errorLabel_name_edit)
                            .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCustomerControlsPanelLayout.createSequentialGroup()
                                    .addComponent(editCustomerButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(edit_success))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        editCustomerControlsPanelLayout.setVerticalGroup(
            editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerControlsPanelLayout.createSequentialGroup()
                .addComponent(customerData_index)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel_edit)
                    .addComponent(nameTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(errorLabel_name_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel_edit)
                    .addComponent(phoneTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(errorLabel_phone_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel_edit))
                .addGap(1, 1, 1)
                .addComponent(errorLabel_email_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCodeTextField_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeLabel_edit))
                .addGap(5, 5, 5)
                .addComponent(errorLabel_posatlCode_edit)
                .addGap(18, 18, 18)
                .addGroup(editCustomerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_success)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editCustomerPanel.add(editCustomerControlsPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(editCustomerPanel, "card2");

        viewAllCustomerPanel.setOpaque(false);
        viewAllCustomerPanel.setLayout(new java.awt.BorderLayout());

        viewAllCustomerTitlePanel.setBackground(new java.awt.Color(202, 62, 71));
        viewAllCustomerTitlePanel.setForeground(new java.awt.Color(255, 255, 255));

        viewAllCustomerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewAllCustomerTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewAllCustomerTitleLabel.setText("View All Customers");
        viewAllCustomerTitlePanel.add(viewAllCustomerTitleLabel);

        viewAllCustomerPanel.add(viewAllCustomerTitlePanel, java.awt.BorderLayout.PAGE_START);

        viewAllCustomerControlsPanel.setOpaque(false);
        viewAllCustomerControlsPanel.setLayout(new java.awt.BorderLayout());

        viewAllCustomerTable.setBackground(new java.awt.Color(82, 82, 82));
        viewAllCustomerTable.setForeground(new java.awt.Color(255, 255, 255));
        viewAllCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Name", "Phone Number", "Email Address", "Postal Code"
            }
        ));
        viewAllCustomerTable.setEnabled(false);
        viewAllCustomerTable.setGridColor(new java.awt.Color(255, 255, 255));
        viewAllCustomerTable.setOpaque(false);
        jScrollPane1.setViewportView(viewAllCustomerTable);

        viewAllCustomerControlsPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        viewAllCustomerPanel.add(viewAllCustomerControlsPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(viewAllCustomerPanel, "card2");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//  Author: Abhi Patel
//  Purpose: Store new customer information.
    private void addCustomerButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButton_addActionPerformed

        String name = nameTextField_add.getText();
        String phone = phoneTextField_add.getText();
        String email = emailTextField_add.getText();
        String postalCode = postalCodeTextField_add.getText();

        isNameFieldVaild = Boolean.parseBoolean((String) (validationMethod.validateNameField(name)).get("isValid"));
        isPhoneFieldVaild = Boolean.parseBoolean((String) (validationMethod.validatePhoneField(phone)).get("isValid"));
        isEmailFieldVaild = Boolean.parseBoolean((String) (validationMethod.validateEmailField(email)).get("isValid"));
        isPostalCodeFieldVaild = Boolean.parseBoolean((String) (validationMethod.validatePostalCodeField(postalCode)).get("isValid"));

        if (isNameFieldVaild && isPhoneFieldVaild && isEmailFieldVaild && isPostalCodeFieldVaild) {
            int customerId = customerMethod.lastCustomerId();

            CustomerData customer = new CustomerData(customerId, name, phone, email, postalCode);

            customerMethod.addCustomer(customer);

            addResultLabel.setForeground(Color.GREEN);
            addResultLabel.setText("Customer added successfully.");
        } else if (name.equals("") || phone.equals("") || email.equals("") || postalCode.equals("")) {
            addResultLabel.setForeground(Color.RED);
            addResultLabel.setText("Please make sure to fill all the text field.");
        } else {
            addResultLabel.setText("");
        }

    }//GEN-LAST:event_addCustomerButton_addActionPerformed

//  Author: Abhi Patel    
    private void clearButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton_addActionPerformed
        resetAddLayout();
    }//GEN-LAST:event_clearButton_addActionPerformed

//  Author: Abhi Patel    
    private void addCustomerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMenuButtonActionPerformed
        resetAllLayouts();

        addCustomerPanel.setVisible(true);
        searchCustomerPanel.setVisible(false);
        editCustomerPanel.setVisible(false);
        viewAllCustomerPanel.setVisible(false);
    }//GEN-LAST:event_addCustomerMenuButtonActionPerformed

//  Author: Abhi Patel    
    private void searchEditCustomerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditCustomerMenuButtonActionPerformed
        resetAllLayouts();

        searchCustomerPanel.setVisible(true);
        addCustomerPanel.setVisible(false);
        editCustomerPanel.setVisible(false);
        viewAllCustomerPanel.setVisible(false);

        editCustomerLink.setVisible(false);

    }//GEN-LAST:event_searchEditCustomerMenuButtonActionPerformed

//  Author: Abhi Patel    
    private void editCustomerLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerLinkMouseClicked
        editCustomerPanel.setVisible(true);
        addCustomerPanel.setVisible(false);
        searchCustomerPanel.setVisible(false);
        viewAllCustomerPanel.setVisible(false);
    }//GEN-LAST:event_editCustomerLinkMouseClicked

//  Author: Abhi Patel    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        resetAllLayouts();
        edit_success.setText("");
        searchCustomerPanel.setVisible(true);
        editCustomerPanel.setVisible(false);
        editCustomerLink.setVisible(false);

    }//GEN-LAST:event_closeButtonActionPerformed

//  Author: Abhi Patel    
    private void viewAllCustomeMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllCustomeMenuButton1ActionPerformed
        viewAllCustomerPanel.setVisible(true);
        addCustomerPanel.setVisible(false);
        searchCustomerPanel.setVisible(false);
        editCustomerPanel.setVisible(false);

        ArrayList<CustomerData> customerList = customerMethod.retriveAllCustomer();

        DefaultTableModel model = (DefaultTableModel) viewAllCustomerTable.getModel();
        model.setRowCount(0);
        for (Object customer : customerList) {
            CustomerData data = (CustomerData) customer;

            String id = String.valueOf(data.getCustomerId());
            String name = data.getName();
            String phone = data.getPhone();
            String email = data.getEmail();
            String pCode = data.getPostalCode();

            String tbData[] = {id, name, phone, email, pCode};

            model.addRow(tbData);
        }
    }//GEN-LAST:event_viewAllCustomeMenuButton1ActionPerformed

    private void validateNameField(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validateNameField
        HashMap validate = null;
        if (evt.getComponent().getName().equals("add")) {
            validate = validationMethod.validateNameField(nameTextField_add.getText());
            errorLabel_name_add.setText(validate.get("msg").toString());
        } else if (evt.getComponent().getName().equals("edit")) {
            validate = validationMethod.validateNameField(nameTextField_edit.getText());
            errorLabel_name_edit.setText(validate.get("msg").toString());
        }

        isNameFieldVaild = Boolean.parseBoolean(validate.get("isValid").toString());
    }//GEN-LAST:event_validateNameField

    private void validatePhoneField(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validatePhoneField
        HashMap validate = null;

        if (evt.getComponent().getName().equals("add")) {
            validate = validationMethod.validatePhoneField(phoneTextField_add.getText());
            errorLabel_phone_add.setText(validate.get("msg").toString());
        } else if (evt.getComponent().getName().equals("edit")) {
            validate = validationMethod.validatePhoneField(phoneTextField_edit.getText());
            errorLabel_phone_edit.setText(validate.get("msg").toString());
        }

        isPhoneFieldVaild = Boolean.parseBoolean(validate.get("isValid").toString());
    }//GEN-LAST:event_validatePhoneField

    private void validateEmailField(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validateEmailField
        HashMap validate = null;

        if (evt.getComponent().getName().equals("add")) {
            validate = validationMethod.validateEmailField(emailTextField_add.getText());
            errorLabel_email_add.setText(validate.get("msg").toString());
        } else if (evt.getComponent().getName().equals("edit")) {
            validate = validationMethod.validateEmailField(emailTextField_edit.getText());
            errorLabel_email_edit.setText(validate.get("msg").toString());
        }

        isEmailFieldVaild = Boolean.parseBoolean(validate.get("isValid").toString());
    }//GEN-LAST:event_validateEmailField

    private void validatePostalCodeField(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validatePostalCodeField
        HashMap validate = null;

        if (evt.getComponent().getName().equals("add")) {
            validate = validationMethod.validatePostalCodeField(postalCodeTextField_add.getText());
            errorLabel_posatlCode_add.setText(validate.get("msg").toString());
        } else if (evt.getComponent().getName().equals("edit")) {
            validate = validationMethod.validatePostalCodeField(postalCodeTextField_edit.getText());
            errorLabel_posatlCode_edit.setText(validate.get("msg").toString());
        }

        isPostalCodeFieldVaild = Boolean.parseBoolean(validate.get("isValid").toString());

    }//GEN-LAST:event_validatePostalCodeField

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (customerIdTextField_search.getText().length() > 0) {
            int customerToSearch = Integer.parseInt(customerIdTextField_search.getText());
            errorLabel_cutomerId_search.setText("");
            ArrayList<CustomerData> customerList = customerMethod.retriveAllCustomer();
            for (Object customer : customerList) {
                CustomerData data = (CustomerData) customer;
                if (customerToSearch == data.getCustomerId()) {
                    searchResultTextArea.setText("Customer Id:" + data.getCustomerId() + "\nName:" + data.getName() + "\nPhone:" + data.getPhone() + "\nPostal Code:" + data.getPostalCode() + "\nEmail:" + data.getEmail());
                    nameTextField_edit.setText(data.getName());
                    emailTextField_edit.setText(data.getEmail());
                    phoneTextField_edit.setText(data.getPhone());
                    postalCodeTextField_edit.setText(data.getPostalCode());
                    customerData_index.setText(Integer.toString(customerList.indexOf(data)));
                    errorLabel_cutomerId_search.setText("");
                    customerData_index.setVisible(false);
                    edit_success.setText("");

                    editCustomerLink.setVisible(true);
                    break;
                } else {
                    editCustomerLink.setVisible(false);

                    errorLabel_cutomerId_search.setText("Customer id is not found!");
                    searchResultTextArea.setText("");
                }
            }
        } else {
            editCustomerLink.setVisible(false);
            
            errorLabel_cutomerId_search.setText("Please Enter Valid customer id");
            searchResultTextArea.setText("");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void editCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerButtonActionPerformed

        String name = nameTextField_edit.getText();
        String phone = phoneTextField_edit.getText();
        String email = emailTextField_edit.getText();
        String postalCode = postalCodeTextField_edit.getText();

        isNameFieldVaild = Boolean.parseBoolean((String) (validationMethod.validateNameField(name)).get("isValid"));
        isPhoneFieldVaild = Boolean.parseBoolean((String) (validationMethod.validatePhoneField(phone)).get("isValid"));
        isEmailFieldVaild = Boolean.parseBoolean((String) (validationMethod.validateEmailField(email)).get("isValid"));
        isPostalCodeFieldVaild = Boolean.parseBoolean((String) (validationMethod.validatePostalCodeField(postalCode)).get("isValid"));

        int customerId = Integer.parseInt(customerData_index.getText());
        edit_success.setText("");

        if (isNameFieldVaild && isPhoneFieldVaild && isEmailFieldVaild && isPostalCodeFieldVaild) {
            ArrayList<CustomerData> customerList = customerMethod.retriveAllCustomer();
            customerList.set(customerId, new CustomerData(++customerId, name, phone, email, postalCode));

            customerMethod.addAllCustomer(customerList);
            edit_success.setForeground(Color.GREEN);
            edit_success.setText("Successfully updated!!");
        } else if (name.equals("") || phone.equals("") || email.equals("") || postalCode.equals("")) {
            edit_success.setForeground(Color.RED);
            edit_success.setText("Please make sure to fill all the text field.");
        } else {
            edit_success.setText("");
        }
    }//GEN-LAST:event_editCustomerButtonActionPerformed

//  Author: Abhi Patel  
    private void only10DigitsAllowed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_only10DigitsAllowed
        char inputChar = evt.getKeyChar();
        if (!((inputChar >= evt.VK_0 && (char) inputChar <= evt.VK_9) || inputChar == evt.VK_BACK_SPACE)) {
            evt.consume();

            if (evt.getComponent().getName().equals("add")) {
                errorLabel_phone_add.setText("Only digits are allowed.");
            } else if (evt.getComponent().getName().equals("edit")) {
                errorLabel_phone_edit.setText("Only digits are allowed.");
            }
        } else {
            if (evt.getComponent().getName().equals("add")) {
                if (!(phoneTextField_add.getText().length() < 10)) {
                    evt.consume();
                } else {
                    errorLabel_phone_add.setText(" ");
                }
            } else if (evt.getComponent().getName().equals("edit")) {
                if (!(phoneTextField_edit.getText().length() < 10)) {
                    evt.consume();
                } else {
                    errorLabel_phone_edit.setText(" ");
                }
            }
        }
    }//GEN-LAST:event_only10DigitsAllowed

//  Author: Abhi Patel  
    private void only6CharAllowed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_only6CharAllowed
        if (evt.getComponent().getName().equals("add")) {
            if (!(postalCodeTextField_add.getText().length() < 6)) {
                evt.consume();
            }
        } else if (evt.getComponent().getName().equals("edit")) {
            if (!(postalCodeTextField_edit.getText().length() < 6)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_only6CharAllowed

//  Author: Abhi Patel
    private void resetAddLayout() {
        nameTextField_add.setText("");
        phoneTextField_add.setText("");
        emailTextField_add.setText("");
        postalCodeTextField_add.setText("");

        errorLabel_email_add.setText(" ");
        errorLabel_name_add.setText(" ");
        errorLabel_phone_add.setText(" ");
        errorLabel_posatlCode_add.setText(" ");

        addResultLabel.setText("");
    }

//  Author: Abhi Patel
    private void resetEditLayout() {
        nameTextField_edit.setText("");
        phoneTextField_edit.setText("");
        emailTextField_edit.setText("");
        postalCodeTextField_edit.setText("");

        errorLabel_email_edit.setText(" ");
        errorLabel_name_edit.setText(" ");
        errorLabel_phone_edit.setText(" ");
        errorLabel_posatlCode_edit.setText(" ");

        edit_success.setText("");
    }
// Author: Abhi Patel
    private void resetSearchLayout() {
        customerIdTextField_search.setText("");
        errorLabel_cutomerId_search.setText(" ");
        searchResultTextArea.setText("");
    }

//  Author: Abhi Patel    
    private void resetAllLayouts() {
        resetAddLayout();
        resetEditLayout();
        resetSearchLayout();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton_add;
    private javax.swing.JPanel addCustomerControlsPanel;
    private javax.swing.JButton addCustomerMenuButton;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JLabel addCustomerTitleLabel;
    private javax.swing.JPanel addCustomerTitlePanel;
    private javax.swing.JLabel addResultLabel;
    private javax.swing.JButton clearButton_add;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel customerData_index;
    private javax.swing.JLabel customerIdLabel_search;
    private javax.swing.JTextField customerIdTextField_search;
    private javax.swing.JButton editCustomerButton;
    private javax.swing.JPanel editCustomerControlsPanel;
    private javax.swing.JLabel editCustomerLink;
    private javax.swing.JPanel editCustomerPanel;
    private javax.swing.JLabel editCustomerTitleLabel;
    private javax.swing.JPanel editCustomerTitlePanel;
    private javax.swing.JLabel edit_success;
    private javax.swing.JLabel emailLabel_add;
    private javax.swing.JLabel emailLabel_edit;
    private javax.swing.JTextField emailTextField_add;
    private javax.swing.JTextField emailTextField_edit;
    private javax.swing.JLabel errorLabel_cutomerId_search;
    private javax.swing.JLabel errorLabel_email_add;
    private javax.swing.JLabel errorLabel_email_edit;
    private javax.swing.JLabel errorLabel_name_add;
    private javax.swing.JLabel errorLabel_name_edit;
    private javax.swing.JLabel errorLabel_phone_add;
    private javax.swing.JLabel errorLabel_phone_edit;
    private javax.swing.JLabel errorLabel_posatlCode_add;
    private javax.swing.JLabel errorLabel_posatlCode_edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel menuTitleLabel;
    private javax.swing.JPanel menuTitlePanel;
    private javax.swing.JLabel nameLabel_add;
    private javax.swing.JLabel nameLabel_edit;
    private javax.swing.JTextField nameTextField_add;
    private javax.swing.JTextField nameTextField_edit;
    private javax.swing.JLabel phoneLabel_add;
    private javax.swing.JLabel phoneLabel_edit;
    private javax.swing.JTextField phoneTextField_add;
    private javax.swing.JTextField phoneTextField_edit;
    private javax.swing.JLabel postalCodeLabel_add;
    private javax.swing.JLabel postalCodeLabel_edit;
    private javax.swing.JTextField postalCodeTextField_add;
    private javax.swing.JTextField postalCodeTextField_edit;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchControlsPanel;
    private javax.swing.JPanel searchCustomerControlsPanel;
    private javax.swing.JPanel searchCustomerPanel;
    private javax.swing.JLabel searchCustomerTitleLabel;
    private javax.swing.JPanel searchCustomerTitlePanel;
    private javax.swing.JButton searchEditCustomerMenuButton;
    private javax.swing.JLabel searchResultLabel;
    private javax.swing.JPanel searchResultPanel;
    private javax.swing.JScrollPane searchResultScrollPane;
    private javax.swing.JTextArea searchResultTextArea;
    private javax.swing.JButton viewAllCustomeMenuButton1;
    private javax.swing.JPanel viewAllCustomerControlsPanel;
    private javax.swing.JPanel viewAllCustomerPanel;
    private javax.swing.JTable viewAllCustomerTable;
    private javax.swing.JLabel viewAllCustomerTitleLabel;
    private javax.swing.JPanel viewAllCustomerTitlePanel;
    // End of variables declaration//GEN-END:variables
}
